version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgres_ctr 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=sreality
      - POSTGRES_HOST=localhost
    ports:
      - 54320:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  aptscraper:
    build:
      dockerfile: /aptscraper/Dockerfile
    volumes:
      - .:/aptscraper
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      dockerfile: /flask_app/Dockerfile
    ports:
      - '8080:5000'
    depends_on:
      - aptscraper

volumes:
  postgres:
    driver: local